language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -U pip
  - pip install -I pytest>=2.8.0
  - pip install -r requirements.txt
  - pip install .
script: py.test -v tests
