dist: bionic
sudo: false
language: python
python:
  - 3.6
  - 3.7
install:
  - pip install -U pip
  - pip install -I pytest>=2.8.0
  - pip install -r requirements.txt
  - pip install .
script: py.test -v tests
